---
- name: Download needed files from binary storage with "{{ user }}" privileges
  get_url: url="{{ item.url }}" dest="{{ item.dest }}" owner="{{ user }}" group="{{ user }}" mode="{{ item.mode }}" url_username=demo_build url_password="{{ demo_build_password }}" force=yes
  with_items:
    - { url: "{{ bin_storage }}/src/git-{{ git_version }}-cos{{ major_version }}.tar.gz", mode: "0644", dest: "/tmp/git-{{ git_version }}-cos{{ major_version }}.tar.gz" }

- name: Download needed files from binary storage with root privileges
  get_url: url="{{ item.url }}" dest="{{ item.dest }}" owner=root group=root mode="{{ item.mode }}" url_username=demo_build url_password="{{ demo_build_password }}" force=yes
  with_items:
    - { url: "{{ bin_storage }}/etc/profile.d/git.sh", mode: "0644", dest: "/etc/profile.d/git.sh" }

- name: Extract git
  unarchive:
    src: "/tmp/git-{{ git_version }}-cos{{ major_version }}.tar.gz"
    dest: "{{ git_parent_path }}"
    owner: root
    group: root
    remote_src: yes

- name: Create symlink 
  file:
    src: "{{ git_parent_path }}/git-{{ git_version }}"
    dest: "/{{ git_parent_path }}/git"
    state: link

- name: Create symlink to git binary (opengrok issues)
  file:
    src: "{{ git_parent_path }}/git/bin/git"
    dest: /bin/git
    state: link

- name: Remove temp files
  shell: rm -rf /tmp/*tar.gz
